### ISSUE TITLE
No connection is active/available to service this operation: EVAL; An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by vnetonline** [zkteco-home/redis-windows#16]
after upgrade to 7.0 i get the following error 

13:31:01 WRN] No connection is active/available to service this operation: EVAL; An existing connection was forcibly closed by the remote host., mc: 1/1/0, mgr: 10 of 10 available, clientName: CANZ-50099848H, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=3,Free=32764,Min=8,Max=32767), v: 2.2.4.27433
StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: EVAL; An existing connection was forcibly closed by the remote host., mc: 1/1/0, mgr: 10 of 10 available, clientName: CANZ-50099848H, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=3,Free=32764,Min=8,Max=32767), v: 2.2.4.27433
 ---> StackExchange.Redis.RedisConnectionException: SocketFailure (ReadSocketError/ConnectionReset, last-recv: 56) on 127.0.0.1:6379/Subscription, Idle/Faulted, last: SUBSCRIBE, origin: ReadFromPipe, outstanding: 0, last-read: 8s ago, last-write: 8s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 7 of 10 available, in: 0, in-pipe: 0, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.2.4.27433
 ---> Pipelines.Sockets.Unofficial.ConnectionResetException: An existing connection was forcibly closed by the remote host.
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 86
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 79
   at Pipelines.Sockets.Unofficial.SocketConnection.DoReceiveAsync() in /_/src/Pipelines.Sockets.Unofficial/SocketConnection.Receive.cs:line 64
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at StackExchange.Redis.PhysicalConnection.ReadFromPipe() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1496
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2760
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.SetAsync(String key, Byte[] value, DistributedCacheEntryOptions options, CancellationToken token)
   at Volo.Abp.Caching.DistributedCache`2.<>c__DisplayClass51_0.<<SetAsync>g__SetRealCache|0>d.MoveNext()
[13:31:01 WRN] ---------- Exception Data ----------
Redis-Multiplexer-Connects = 1/1/0
Redis-Manager = 10 of 10 available
Redis-Client-Name = CANZ-50099848H
Redis-ThreadPool-IO-Completion = (Busy=0,Free=1000,Min=8,Max=1000)
Redis-ThreadPool-Workers = (Busy=3,Free=32764,Min=8,Max=32767)
Redis-Busy-Workers = 3
Redis-Version = 2.2.4.27433
redis-command = EVAL
request-sent-status = WaitingToBeSent

**Comment by zkteco-home** [comment]
thanks, i will check,but i can't get useful information from your logs,Redis-version:2.2.4? command detail?EVAL Lua script?i hope you can tell me what command make it wrong

**Comment by vnetonline** [comment]
I am using abp Framework and doing development on my local machine and visual sudio give me this error when abp framework is access Redis to store information

**Comment by zkteco-home** [comment]
your redis-server version?  what redis command? your logs is not reported by redis-server

**Comment by zkteco-home** [comment]
your redis-server version?  what redis command? your logs is not reported by redis-server

**Comment by vnetonline** [comment]
> your redis-server version?  what redis command? your logs is not reported by redis-server

I am using the latest release you have made 7.0

**Comment by zkteco-home** [comment]
you can refer to #11,that developer also use StackExchange.Redis,finally working fine.
when you test,first dont install it as service,start redis-server manually via cmd and observe if there is error report.i guess your problem is connect issue.
