### ISSUE TITLE
Redis crashes after a while

### ISSUE THREAD

**Issue by gurc4n** [zkteco-home/redis-windows#9]
Redis crashes after a while. It is random. I cannot see a regular time schema.
After that problem, there will be a lot of from this error message: Error registering fd event for the new client: No error

**Comment by gurc4n** [comment]
Exception in the client : 
[13:11:19.895] [ERR] { ThreadId: 60 }  No connection is active/available to service this operation: GET CH:coreGetCNCDeviceByMachine-1947848840; An established connection was aborted by the software in your host machine, mc: 1/1/0, mgr: 10 of 10 available, clientName: XXXXXXXXXXXXX, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=2,Free=32765,Min=16,Max=32767), v: 2.2.88.56325
StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: GET CH:coreGetCNCDeviceByMachine-1947848840; An established connection was aborted by the software in your host machine, mc: 1/1/0, mgr: 10 of 10 available, clientName: EPDI-WEB01b71cfb44-36bf-4694-8a03-23c35315ff4c, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=2,Free=32765,Min=16,Max=32767), v: 2.2.88.56325 ---> StackExchange.Redis.RedisConnectionException: SocketFailure (ReadEndOfStream, 0-read, last-recv: 0) on XXXXXXXXXXX/Subscription, Flushing/NotStarted, last: SUBSCRIBE, origin: OnEstablishingAsyncAwaited, outstanding: 3, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.88.56325 ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 74
   at Pipelines.Sockets.Unofficial.SocketConnection.<DoSendAsync>d__81.MoveNext() in /_/src/Pipelines.Sockets.Unofficial/SocketConnection.Send.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetFlushResult(FlushResult& result)
   at System.IO.Pipelines.Pipe.PrepareFlush(CompletionData& completionData, ValueTask`1& result, CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.FlushAsync(CancellationToken cancellationToken)
   at Pipelines.Sockets.Unofficial.SocketConnection.WrappedWriter.FlushAsync(CancellationToken cancellationToken) in /_/src/Pipelines.Sockets.Unofficial/SocketConnection.cs:line 432
   at StackExchange.Redis.PhysicalConnection.FlushAsync() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 286
   at StackExchange.Redis.ServerEndPoint.<HandshakeAsync>d__120.MoveNext() in /_/src/StackExchange.Redis/ServerEndPoint.cs:line 885
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StackExchange.Redis.ServerEndPoint.<OnEstablishingAsyncAwaited>d__97.MoveNext() in /_/src/StackExchange.Redis/ServerEndPoint.cs:line 566
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2863
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2433
   at CommonUtils.RedisWrapper.StringGet(String key, String prefix) in

**Comment by zkteco-home** [comment]
you tell me your email,i send redis 7.0 to you

**Comment by zkteco-home** [comment]
> gurcan [@] gmail [.] com

your email has been returned,you send it to my email:  my9988@126.com

**Comment by zkteco-home** [comment]
sorry to delay,i reproduced your issue and solved it,please pull redis 7.0

**Comment by Arnacels** [comment]
Hi, I have same error with latest version, can you help me?

`[10256] 23 Feb 11:19:34.488 * monotonic clock: POSIX clock_gettime
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 7.0.0 (02/14/2022/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 10256
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           https://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'

[10256] 23 Feb 11:19:34.491 # Server initialized
[10256] 23 Feb 11:19:34.492 * The AOF directory appendonlydir doesn't exist
[10256] 23 Feb 11:19:34.492 * Loading RDB produced by version 7.0.0
[10256] 23 Feb 11:19:34.492 * RDB age 2831 seconds
[10256] 23 Feb 11:19:34.493 * RDB memory usage when created 0.71 Mb
[10256] 23 Feb 11:19:34.493 * Done loading RDB, keys loaded: 0, keys expired: 0.
[10256] 23 Feb 11:19:34.493 * DB loaded from disk: 0.001 seconds
[10256] 23 Feb 11:19:34.493 * Ready to accept connections


=== REDIS BUG REPORT START: Cut & paste starting from here ===
[10256] 23 Feb 11:19:55.675 # --- EXCEPTION_ACCESS_VIOLATION
[10256] 23 Feb 11:19:55.676 # --- STACK TRACE
redis-server.exe!((null):0)(0x1401DCF10, 0x0014FF60, 0x0014E960, 0x0014E960)
redis-server.exe!((null):0)(0x0014E960, 0x0014FF01, 0x140114430, 0x14011E250)
KERNELBASE.dll!UnhandledExceptionFilter((null):0)(0x00000000, 0x7FFC11C82020, 0x00000000, 0x00000000)
ntdll.dll!memset((null):0)(0x00000000, 0x00000000, 0x0014F5F0, 0x0014EF28)
ntdll.dll!_C_specific_handler((null):0)(0x00000000, 0x0014EF10, 0x00000000, 0x140000000)
ntdll.dll!_chkstk((null):0)(0x0014EF10, 0x00000000, 0x7FFC1194CC3C, 0x7FFC118A0000)
ntdll.dll!RtlWalkFrameChain((null):0)(0x00000000, 0x00000000, 0x7FEB16028000, 0x00000000)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x02A7ECE0, 0x0014F8F9, 0x0014F8F2, 0x7FEB00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0xFFFFFFFFFFFFFFFF, 0x7FEB16028000, 0x02A7ECE0, 0x7FEB16028000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x1D828A748FEE501, 0x0000000F, 0x00000000, 0x00000001)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x14005C2F0, 0x00000000, 0x00000001, 0x7FEB1602D065)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000060, 0x7FEB00000000, 0x00000001, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x7FEB16028000, 0x7FEB16028000, 0x00000000, 0x7FEB16028000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000082, 0x7FEB16028000, 0x00000000, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0000000D, 0x7FEB080002A0, 0x00000000, 0x00000001)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0xFFFFFFFF0000001B, 0x00000001, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00002810, 0x1401D6C50, 0x7FEAFF800008, 0x7FEB05C00E70)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x004EAF50, 0x004EAF50, 0x004EAF50, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x004EAF50, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[10256] 23 Feb 11:19:55.680 #
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report this bug by following the instructions at:

     https://github.com/zkteco-home/redis-windows/wiki/Submitting-an-Issue

    Suspect RAM error? Use redis-server --test-memory to verify it.


PS C:\Users\Administrator\radflow\redis> git pull
Already up to date.
PS C:\Users\Administrator\radflow\redis>`

**Comment by zkteco-home** [comment]
is issue still there?
